"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-30 16:31:05.671655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SUCCEEDED', 'FAILED', 'ROLLED_BACK', name='deploymentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployments'))
    )
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.create_index('ix_deployments_service_name_timestamp', ['service_name', 'timestamp'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('DETECTED', 'INVESTIGATING', 'ANALYZING', 'AWAITING_APPROVAL', 'REMEDIATING', 'VERIFYING', 'RESOLVED', 'FAILED', 'ESCALATED', name='incidentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('service_name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_service_name'), ['service_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)

    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARN', 'ERROR', name='loglevel', native_enum=False, length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logs'))
    )
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_index('ix_logs_service_name_timestamp', ['service_name', 'timestamp'], unique=False)

    op.create_table('service_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('HEALTHY', 'DEGRADED', 'DOWN', name='servicestatus', native_enum=False, length=32), nullable=False),
    sa.Column('error_rate', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('cpu_usage', sa.Float(), nullable=False),
    sa.Column('memory_usage', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_health'))
    )
    with op.batch_alter_table('service_health', schema=None) as batch_op:
        batch_op.create_index('ix_service_health_service_name_timestamp', ['service_name', 'timestamp'], unique=False)

    op.create_table('agent_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.Enum('orchestrator', 'investigation', 'root_cause', 'remediation', 'verification', name='agentname', native_enum=False, length=32), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_agent_events_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_events'))
    )
    with op.batch_alter_table('agent_events', schema=None) as batch_op:
        batch_op.create_index('ix_agent_events_incident_id_timestamp', ['incident_id', 'timestamp'], unique=False)

    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.Enum('orchestrator', 'investigation', 'root_cause', 'remediation', 'verification', name='agentname', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='agentrunstatus', native_enum=False, length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('output', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_agent_runs_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_incident_id'), ['incident_id'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('ROLLBACK_DEPLOYMENT', 'RESTART_SERVICE', 'NO_ACTION', 'ESCALATE_TO_HUMAN', name='actiontype', native_enum=False, length=32), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('risk', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel', native_enum=False, length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='approvalstatus', native_enum=False, length=32), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_approvals_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_incident_id'), ['incident_id'], unique=False)

    op.create_table('incident_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('recovery_status', sa.Enum('RECOVERED', 'NOT_RECOVERED', 'NOT_ATTEMPTED', name='recoverystatus', native_enum=False, length=32), nullable=False),
    sa.Column('report', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_reports_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_reports')),
    sa.UniqueConstraint('incident_id', name=op.f('uq_incident_reports_incident_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_reports')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_incident_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_incident_id'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('agent_events', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_events_incident_id_timestamp')

    op.drop_table('agent_events')
    with op.batch_alter_table('service_health', schema=None) as batch_op:
        batch_op.drop_index('ix_service_health_service_name_timestamp')

    op.drop_table('service_health')
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index('ix_logs_service_name_timestamp')

    op.drop_table('logs')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_incidents_service_name'))

    op.drop_table('incidents')
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_index('ix_deployments_service_name_timestamp')

    op.drop_table('deployments')
    # ### end Alembic commands ###
