"""cicd events

Normalized CI/CD telemetry from GitHub webhooks (push, workflow_run, deployment_status). A new
table is needed: deployments cannot represent commits, builds, tests or failed runs, and
agent_events requires an incident. `delivery_id` is unique (idempotent redeliveries) and
`deployment_key` is unique (one deployment per workflow run attempt). Row level security is
enabled like every other table (see 0002).

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-01 00:22:16.231263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cicd_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('delivery_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('category', sa.Enum('COMMIT', 'BUILD', 'TEST', 'DEPLOYMENT', name='cicdcategory', native_enum=False, length=32), nullable=False),
    sa.Column('repository', sa.String(length=140), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('commit_sha', sa.String(length=40), nullable=True),
    sa.Column('commit_message', sa.String(length=200), nullable=True),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('workflow_name', sa.String(length=100), nullable=True),
    sa.Column('workflow_run_id', sa.BigInteger(), nullable=True),
    sa.Column('run_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'IN_PROGRESS', 'COMPLETED', name='cicdstatus', native_enum=False, length=32), nullable=False),
    sa.Column('conclusion', sa.Enum('SUCCESS', 'FAILURE', 'CANCELLED', 'TIMED_OUT', 'NEUTRAL', 'SKIPPED', 'OTHER', name='cicdconclusion', native_enum=False, length=32), nullable=True),
    sa.Column('service_name', sa.String(length=64), nullable=True),
    sa.Column('environment', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('version_source', sa.String(length=32), nullable=True),
    sa.Column('html_url', sa.String(length=300), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=True),
    sa.Column('deployment_key', sa.String(length=200), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], name=op.f('fk_cicd_events_deployment_id_deployments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cicd_events')),
    sa.UniqueConstraint('delivery_id', name=op.f('uq_cicd_events_delivery_id')),
    sa.UniqueConstraint('deployment_key', name=op.f('uq_cicd_events_deployment_key'))
    )
    with op.batch_alter_table('cicd_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cicd_events_commit_sha'), ['commit_sha'], unique=False)
        batch_op.create_index(batch_op.f('ix_cicd_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cicd_events_repository'), ['repository'], unique=False)
        batch_op.create_index('ix_cicd_events_service_name_occurred_at', ['service_name', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cicd_events_workflow_run_id'), ['workflow_run_id'], unique=False)

    # ### end Alembic commands ###
    if op.get_context().dialect.name == "postgresql":
        op.execute("ALTER TABLE cicd_events ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cicd_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cicd_events_workflow_run_id'))
        batch_op.drop_index('ix_cicd_events_service_name_occurred_at')
        batch_op.drop_index(batch_op.f('ix_cicd_events_repository'))
        batch_op.drop_index(batch_op.f('ix_cicd_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_cicd_events_commit_sha'))

    op.drop_table('cicd_events')
    # ### end Alembic commands ###
