"""code reviews

AI code reviews of pushes to monitored projects (one row per repository + commit; the unique
constraint makes webhook redeliveries and repeated pushes idempotent). Additive; row level security
is enabled like every other table (see 0002).

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-01 06:59:31.356765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository', sa.String(length=140), nullable=False),
    sa.Column('service_name', sa.String(length=64), nullable=False),
    sa.Column('cicd_event_id', sa.Integer(), nullable=True),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('base_sha', sa.String(length=40), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('commit_message', sa.String(length=200), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'SKIPPED', name='codereviewstatus', native_enum=False, length=32), nullable=False),
    sa.Column('risk', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel', native_enum=False, length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('findings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('files', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('skipped_files', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cicd_event_id'], ['cicd_events.id'], name=op.f('fk_code_reviews_cicd_event_id_cicd_events'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_code_reviews')),
    sa.UniqueConstraint('repository', 'commit_sha', name=op.f('uq_code_reviews_repository'))
    )
    with op.batch_alter_table('code_reviews', schema=None) as batch_op:
        batch_op.create_index('ix_code_reviews_service_name_created_at', ['service_name', 'created_at'], unique=False)

    # ### end Alembic commands ###
    if op.get_context().dialect.name == "postgresql":
        op.execute("ALTER TABLE code_reviews ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_code_reviews_service_name_created_at')

    op.drop_table('code_reviews')
    # ### end Alembic commands ###
